"""add comment, pitch, downvote and upvote class

Revision ID: 2b68f9fc6762
Revises: f5caad06295b
Create Date: 2022-05-10 18:06:37.997308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b68f9fc6762'
down_revision = 'f5caad06295b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
